### ISSUE TITLE
Change design for pre_load_hooks

### ISSUE THREAD

**Issue by danrgll** [automl/neps#100]
from:
```yaml
pre_load_hooks:
  hook1:
    path: "path/to/your/hooks.py"
    name: hook1
```
to:
```yaml
    pre_load_hooks:
        hook1: path/to/your/hooks.py # (function_name: Path to the function's file)
```
