### ISSUE TITLE
Enable the use of dict for pipeline_space when the custom optimizer is defined via yaml

### ISSUE THREAD

**Issue by danrgll** [automl/neps#87]
Using a Custom optimizer (class) via yaml currently only works if pipeline_space is also provided via a yaml.

```yaml
run_args:
     pipeline_space: <path_to_yaml_file>
     searcher:
        path: <path_to_custom_searcher_class>
        name: <class_name>
```
